// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import FlashController from "./flash_controller"
import DarkModeToggleController from "./dark_mode_toggle_controller"
import ModalController from "./modal_controller"
import SumUpdaterController from "./sum_updater_controller"
application.register("hello", HelloController)
application.register("flash", FlashController)
application.register("dark-mode-toggle", DarkModeToggleController)
application.register("modal", ModalController)
application.register("sum-updater", SumUpdaterController)
import "./railsui"
