name: Deploy to Production

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - config/deploy_with_ci

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: deploy-production
    concurrency:
      group: production_environment
      cancel-in-progress: true
    environment:
      name:  production
      url: https://goals.rest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup
        uses: ./.github/workflows/setup
        id: setup
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          aws-role-access: ${{ secrets.AWS_ROLE_ACCESS }}

      - name: Kamal Deploy
        uses: igor-alexandrov/kamal-deploy@v0.4.1
        with:
          registry-username: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          environment: production
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          GOALS_DOCKER_IMAGE: ${{ secrets.GOALS_DOCKER_IMAGE }}
          GOALS_SERVER_IP: ${{ secrets.GOALS_SERVER_IP }}
          GOALS_HOST: ${{ secrets.GOALS_HOST }}
          KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          GOALS_SSH_USER: ${{ secrets.GOALS_SSH_USER }}
